name: Fuzz

on:
  release:
    types: [created, edited]

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: fuzz tests
        run: go test --tags=fuzz -run TestFuzzServer_Install -v
