name: Fuzz

on:
  release:
    types: [created, edited]

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.20.0'

    - name: fuzz tests
      run: go test --tags=fuzz -run TestFuzzServer_Install -v

    - name: Package
      run: |
        make
        mkdir vin-linux-x86_64
        cp vin vind vin-linux-x86_64
        tar cvvjf vin-linux-x86_64.tar.bz2 vin-linux-x86_64
        tar czf empty.tar.gz -T /dev/null

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          vin-linux-x86_64.tar.bz2
          empty.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
