name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Lint
      uses: Jerome1337/golint-action@v1.0.2
      with:
        golint-path: './src/...'

    - name: Build
      run: make

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out ./...

    - name: Go test install
      run: sudo make install

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.8

    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov

    - name: Package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir vin-linux-x86_64
        cp vin vind vin-dist
        tar cvvjf vin-linux-x86_64.tar.bz2 vin-linux-x86_64
        tar czf empty.tar.gz -T /dev/null

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          vin-linux-x86_64.tar.bz2
          empty.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -covermode=count -coverprofile=coverage.out ./...

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
